plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.2'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

description = 'Demo project for Spring Boot'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

ext {
    set('springCloudVersion', '2025.1.2')
    set('mapstructVersion', '1.5.5.Final')
}

repositories {
    mavenCentral()
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

dependencies {

    // =========================
    // Spring Boot
    // =========================
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'

    // =========================
    // DevTools
    // =========================
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // =========================
    // Lombok
    // =========================
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // =========================
    // MapStruct
    // =========================
    implementation "org.mapstruct:mapstruct:${mapstructVersion}"
    annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"

    // =========================
    // PostgreSQL
    // =========================
    runtimeOnly 'org.postgresql:postgresql'

    // =========================
    // Spring Security Crypto
    // =========================
    implementation 'org.springframework.security:spring-security-crypto'

    // =========================
    // Eureka Client
    // =========================
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'

    // =========================
    // Tests
    // =========================
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-validation-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation 'org.springframework.security:spring-security-test'
}

tasks.named('test') {
    useJUnitPlatform()
}